osx_image: xcode8.3
language: objective-c
cache:
  - bundler
  - cocoapods
branches:
  only:
    - develop
    - master
notifications:
  email: false
before_install:
  - brew update
  - gem install bundler
  - bundle install && brew bundle
  - bundle exec pod repo update
script:
  - bundle exec fastlane run_tests
after_success:
  - bundle exec fastlane ci_framework_deploy
